[package]
name = "ftb-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
druid = "0.8.3"
reqwest = "0.12.9"
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
